pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'MasaMaven'
            url = 'https://masa.dy.fi/maven'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'carpet-hao-addition-26.2'
